# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef6c1c1bf4d701c043c74e6ee96a9bf287ed1b9167b3948104bd0e5ad14a495647fa89231d7feeda5e45e2121924a86e356c4dac2bf30554ac9955fae87ee509

test:
  secret_key_base: 7ec8d6bfcb633c47be866e3e4deb43243bb7d2f394b3034282c4585c0fa531429d8738b9df5a04b8adf234fd5404b5e5135e88346f2e8023951bc1e762f38c3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
